MessageBoard/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using System.Web.Mvc;
using MessageBoard.Models;
using MessageBoard.Services;
using System.Runtime.InteropServices;

namespace MessageBoard.Controllers
{
    public class PortfolioController : Controller
    {
        private PortfolioService service;

        public PortfolioController()
        {
            this.service = new PortfolioService();
        }

        public ActionResult Index()
        {
            IEnumerable<PictureVM> vms = this.service.GetPictureVms();
            return View(vms);
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Add()
        {
            return this.View();
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Add([Bind(Include = "ImageThumbnail")] PictureBM bind)
        {
                this.service.AddPicture(bind);
                return this.RedirectToAction("Index");

        }

    }
}

MessageBoard/Views/Portfolio/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h1>Add URL Of The New Picture</h1>
<br />
@using (Html.BeginForm("Add", "Portfolio", FormMethod.Post))
{
    <div class="form-group">
        @Html.Editor("ImageThumbnail", new { htmlAttributes = new { @class = "form-control" } })
        <br />
        <input type="submit" value="Add" class="btn btn-primary btn-large" />
    </div>
    <br/>
    <br/>

    <h1>Or Upload From Your PC</h1>

    <input type="file" name="file"/>
    <br/>
    <input type="submit" name="Submit" id="Submit" value="Upload" class="btn btn-success btn-large"/>
}

MessageBoard/Views/Portfolio/Index.cshtml
@model IEnumerable<MessageBoard.Models.PictureVM>
@{
    ViewBag.Title = "Index";
}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="span12 hidden-desktop">
                <div class="padd"><div class="navis"></div></div>
            </div>
            <div class="span12">
                <div class="whity content">
                    <!-- Content should be encloased inside div with the class "posts" -->
                    <div class="posts">
                        <!-- Each entry should be enclosed inside div with the class "entry" -->
                        <div class="entry">
                            <div class="padd">
                                <!-- Portfolio title -->
                                <h2>Portfolio</h2>
                                <!-- Portfolio para -->
                                <!-- Add class "alignleft" to image to align left. -->
                                <a href="/Portfolio/add" class="btn btn-large btn-primary">Add Picture</a>
                                <br />
                                <p>
                                    <!-- Add filter names inside "data-filter". For example ".web-design", ".seo", etc., Filter names are used to filter the below images. -->
                                    <ul id="filters">
                                        <li><a href="#" data-filter="*" class="label label-info">All</a></li>
                                        <li><a href="#" data-filter=".one" class="label label-info">One</a></li>
                                        <li><a href="#" data-filter=".two" class="label label-info">Two</a></li>
                                        <li><a href="#" data-filter=".three" class="label label-info">Three</a></li>
                                        <li><a href="#" data-filter=".four" class="label label-info">Four</a></li>
                                        <li><a href="#" data-filter=".five" class="label label-info">Five</a></li>
                                    </ul>
                                </p>

                                <div id="portfolio-big">
                                    <!-- Add the above used filter names inside div tag. You can add more than one filter names. For image lightbox you need to include "a" tag pointing to image link, along with the class "prettyphoto".-->
                                    
                                    
                                    @foreach (var pic in Model)
                                    {
                                        <div class="element five two"><a href="@pic.ImageThumbnail" class="prettyphoto"><img src="@pic.ImageThumbnail" alt="" /></a></div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="mobily hidden-desktop">

            </div>
        </div>
    </div>
</div> 